### ISSUE TITLE
texture loading changing format

### ISSUE THREAD

**Issue by eliyam32** [glmark2/glmark2#47]
Hi, 
In the terrain benchmark, you are using jpg files : terrain - *.jpg
which are not up to date, so instead I tried to  convert them to pngs , but they are not rendered correctly.

any advice on how to render the terrain correctly with png textures ?

**Comment by afrantzis** [comment]
Hi, have you removed the jpg versions from the data directory? If not, glmark2 may end up choosing a mix of png and jpg files for the textures (depending in inode order in the directory). This would not be an issue normally, but since you seem to have an issue with jpegs, this mix could cause problems.

If the above doesn't fix the issue, could you please upload a screenshot of what you get? FWIW, I did a quick check converting all terrain jpgs to pngs, removed terrain jpgs from data/, and all seems to work fine for me.

**Comment by afrantzis** [comment]
Also, please make sure that glmark2 is using the correct path for the data directory. You can set it at ./waf configure time using the "--data-path=absolute-data-path" flag.

**Comment by eliyam32** [comment]
Hi, 

> have you removed the jpg versions from the data directory?

Yes, I exactly for the reason you mentioned.

> FWIW, I did a quick check converting all terrain jpgs to pngs, removed terrain jpgs from data/, and all seems to work fine for me.

Great! 
do you mind uploading the converted files ? 

> could you please upload a screenshot of what you get?

see attached

**Comment by afrantzis** [comment]
Sure, here are the converted files:

![terrain-backgrounddetailed6](https://user-images.githubusercontent.com/495575/35872592-e4657ba8-0b6f-11e8-93e6-9ed7b9ab0d05.png)
![terrain-grasslight-512](https://user-images.githubusercontent.com/495575/35872603-ec72d1d8-0b6f-11e8-8407-0d1315807ef2.png)
![terrain-grasslight-512-nm](https://user-images.githubusercontent.com/495575/35872605-ec9f01e0-0b6f-11e8-8131-52b22d06ab5e.png)

Not sure what I am seeing in the screenshot you attached. Is this the terrain grass somehow rendered blue, or ...?
