### ISSUE TITLE
desktop benchmark

### ISSUE THREAD

**Issue by eliyam32** [glmark2/glmark2#48]
Hi, 
quick question , 
in SceneDesktop::setup() , line 845, "Set up the screen and desktop RenderObjects " : 
what is the use of priv_->screen ?
I can understand its use for offscreen , but not for regular screen rendering.
specifically , there is no RenderObject::fbo_ to apply to in the onscreen case 

thanks , 
EM

**Comment by afrantzis** [comment]
Hi! The RenderScreen object is also used in the onscreen case, since it ensures that any offscreen FBOs are disabled when drawing to the screen. In particular, the fbo_ used in that case will be 0, thus glBindFramebuffer(GL_FRAMEBUFFER, 0) in RenderObject::make_current() will unbound any active FBOs and bind the window system framebuffer (i.e. the one on the screen) before rendering. HTH.
