### ISSUE TITLE
Android FPS and off-screen rendering

### ISSUE THREAD

**Issue by eliyam32** [glmark2/glmark2#49]
Hi, 
The glmark2 runs successfully on Android , however the FPS is limited to 60. 
I assumed the way to bypass that is to enable Options::offscreen = true , this made no difference. 
Reading the readme https://github.com/glmark2/glmark2/blob/master/README.android 
it seems to be a known issue ? ( Android limitations … off-screen )

please advise how to generate true FPS on Android, 
Thanks, 
EM

**Comment by eliyam32** [comment]
@afrantzis

**Comment by afrantzis** [comment]
Hi! glmark2 is telling Android to run without vsync, but in my experience most drivers just disregard this hint. Two possible workarounds:

1. As you said, one way is to add support for offscreen surfaces. In the Android case, Android is responsible for setting up the surface etc, so a good place to start would be android/src/org/linaro/glmark2/Glmark2SurfaceView.java, although I expect it to require significant changes. If you search online there a few posts that describe how to render to an FBO on Android, but since I don't have first hand experience I cannot vouch about their correctness.

2. Draw on screen but somehow turn off vsync. On some devices it is possible, using some device specific way, to tell the driver to turn off vsync.

**Comment by eliyam32** [comment]
Hi, 
Correction : Option 2 is not possible, since vsync is a restriction imposed by the Android framework not the driver.
I will try to implement option 2 then, any pointers are welcome.
Thanks, 
EM

**Comment by eliyam32** [comment]
Hi, 
few more questions,
is there a difference between on-screen and off-screen rendering ? 
how to make sure they are equivalent ?  
also : there is offscreen rendering to a renderbuffer vs render to texture? pixel format differences etc
