### ISSUE TITLE
tear down of EGL context

### ISSUE THREAD

**Issue by eliyam32** [glmark2/glmark2#51]
Hi, I have not found the code that tears down the EGL context: 

something like the following snippet : 
static void term_display() {
         if (display != EGL_NO_DISPLAY) {
         eglMakeCurrent(display, EGL_NO_SURFACE, EGL_NO_SURFACE, EGL_NO_CONTEXT);
         if (context != EGL_NO_CONTEXT) {
             eglDestroyContext(display, context);
         }
         if (surface != EGL_NO_SURFACE) {
             eglDestroySurface(display, surface);
         }
         eglTerminate(display);
     }
     display = EGL_NO_DISPLAY;
     context = EGL_NO_CONTEXT;
     surface = EGL_NO_SURFACE;
}

**Comment by afrantzis** [comment]
Hi, there is currently no code in glmark2 to perform explicit EGLSurface/EGLDisplay teardown, since the EGL resources are implicitly released during program shutdown and we don't have a need for more controlled resource release during execution. That being said, I wouldn't be against having the explicit EGL teardown code.

There is code to destroy the EGLContext in GLStateEGL::reset() which is called before each benchmark to start it with a clean context (unless the --reuse-context flag is specified).

**Comment by afrantzis** [comment]
As luck would have it, I recently received a patch to perform the EGL teardown. It uses the concise (but equally correct) form of termination with eglTerminate + eglReleaseThread, rather than the more explicit destruction of resources. I have applied it at https://github.com/glmark2/glmark2/commit/9c37ce30bf494c667a585c9840308e1514e23f65
